spring:
  servlet:
    multipart:
      # 默认单文件只能 1MB，视频必挂，这里放大
      max-file-size: 100MB
      max-request-size: 100MB
  data:
    redis:
      host: 121.199.38.195
      port: 6379
      password: 200567
      database: 0
      timeout: 5000ms
  rabbitmq:
    host: 121.199.38.195  
    port: 5672                  
    username: guest           
    password: guest            
    virtual-host: /                 
  mail:
    host: smtp.qq.com           
    port: 465                  
    username: 2322672114@qq.com    
    password: 
    protocol: smtps             
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
jwt:
  secret: wksjdnzhduejduskeisjeiskehjwpzws
